# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f3608b8ab39524314d574ce06abc86c47b9040dd6bd3751b2348eb58ad8180524d8d7904d5c10d02ca6b7a36f2ed4ae16b71ef239380aadc92317c4d3735c36

test:
  secret_key_base: 946d468862956551db754ce6f7a9ade5152a2128f9780dca2e59979b6b0b1a6e26f7e023e70202be3cb1fb5d11e3ac1f787f03988039b8eedc766652328dfbfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
